### ISSUE TITLE
Add Mention of Ghost Characters?

### ISSUE THREAD

**Issue by donatj** [Codepoints/awesome-codepoints#10]
There are a number of characters in Unicode that made their way in from JIS that aren't actual Japanese characters.

https://www.dampfkraft.com/ghost-characters.html

**Comment by Boldewyn** [comment]
Yes, that’s a good idea! If I remember correctly, I thought adding them, when I read the article for the first time, but forgot.

If you want to take a stab at it, I accept pull requests. Otherwise I’ll add them as soon as I find time to do.
