### ISSUE TITLE
Hash characters

### ISSUE THREAD

**Issue by edent** [Codepoints/awesome-codepoints#11]
Websites like Twitter often use `#` for folksonomy tagging. But there are two different hash symbols! There’s the # we all know and love [U+0023], and there’s ＃.  Looks pretty similar, but in fact it’s the Unicode symbol [U+FF03] 'FULLWIDTH NUMBER SIGN'

My understanding is that Japanese keyboards tend to use the fullwidth version, so sites accept both for hashtags.

Would you be interested in a PR for it?

**Comment by Boldewyn** [comment]
Yes, thank you! That sounds indeed like a good addition.
