### ISSUE TITLE
Irony mark description not ironic

### ISSUE THREAD

**Issue by ubipo** [Codepoints/awesome-codepoints#13]
I may be missing something here but the description for the irony mark (1), when applying irony would be "Not a useful character".

But it is useful right? Or is it not since it is so rarely used?

The too options are:
1. "A useful character⸮" (current, implies "Not a useful character")
2. "It is a completely useless character⸮" (my suggestion, implies "It is a useful character")

I was about to create a pull request but as I said I may be misinterpreting the irony.

(1) "U+2E2E REVERSED QUESTION MARK - the “irony mark” to express irony/sarcasm. A useful character⸮"

**Comment by Boldewyn** [comment]
It is a well-constructed paradoxon. _If_ you believe, the irony mark is useless, then you have to agree to the irony of “A useful character⸮“, letting the mark do its work. If you believe the opposite, that it is a usefull mark, then “A useful character⸮”, you have to negate the sentence, which renders the mark useless.

It’s a bit like the Crete Epimenides saying, “All Cretans are liars.”

OK, now that I accomplished after-the-fact interpreting a philosophical background onto the sentence, the true inspiration for the sentence was this Simpsons scene:
https://www.youtube.com/watch?v=mSy5mEcmgwU
:-)
