### ISSUE TITLE
Minor issue in Regional Indicator Symbols

### ISSUE THREAD

**Issue by tonton-pixel** [Codepoints/awesome-codepoints#14]
The last two examples of Regional Indicator Symbols display a code point value outside the range `[U+1F1E6, U+1F1FF]`; this is obviously a typo:

`U+0F1EA` and `U+0F1F3` should be `U+1F1EA` and `U+1F1F3`, respectively.

Country | ISO Code | Code Points | Emoji (if supported)
-- | -- | -- | --
USA | US | U+1F1FA + U+1F1F8 | 🇺🇸
Germany | DE | U+1F1E9 + **U+1F1EA** | 🇩🇪
China | CN | U+1F1E8 + **U+1F1F3** | 🇨🇳

Thanks for this awesome list!

**Comment by Boldewyn** [comment]
Oh, indeed! Thank you for noticing! I’ve fixed it.
