### ISSUE TITLE
Add whether codepoints work on most terminals

### ISSUE THREAD

**Issue by ehmicky** [Codepoints/awesome-codepoints#15]
I have created [a list of all codepoints](https://github.com/ehmicky/cross-platform-terminal-characters) that work on most terminals.
I am wondering whether that list could reference this repository, and vice-versa? It seems like they share a similar theme and readers might be interested in both resources.

**Comment by Boldewyn** [comment]
Yep, good idea! Thanks for the suggestion, I’ve added a link to it in a new section “Other Lists of Code Points”.

**Comment by ehmicky** [comment]
Thanks! I have added a link to `awesome-codepoints` myself in https://github.com/ehmicky/cross-platform-terminal-characters#see-also :)

**Comment by ehmicky** [comment]
Interesting side note: I have gone through `awesome-codepoints` and it seems like the only characters that would work on most terminals are U+00A0 (no break space) and [a subset of Box Drawing](https://github.com/ehmicky/cross-platform-terminal-characters/blob/main/README.md#box-drawing) (U+2500 to U+257F). Even Block Elements (U+2580 to U+259F) are not supported on some terminals. 

The small overlap is probably due to `awesome-codepoints` documenting more "exotic" codepoints, which are therefore less likely to work on some minor terminals (like cmd.exe, xterm, or the Linux console).
