### ISSUE TITLE
U+10FFFF is the last defined character

### ISSUE THREAD

**Issue by behnam** [Codepoints/awesome-codepoints#6]
This paragraph is not that accurate:

> * [U+EFFFF](https://codepoints.net/U+EFFFF) (_non-character_) - last (currently defined) code point. [U+10FFFF](https://codepoints.net/U+10FFFF) is the ultimately last one, but it is a private use character, that is guaranteed to be never defined by Unicode.

U+10FFFF has the exact same status of U+EFFFF, even being on Plane 16.

From the [FAQ](https://www.unicode.org/faq/private_use.html#noncharacters):
> A: The 66 noncharacters are allocated as follows:
> [...]
> the last two code points of each of the 16 supplementary planes: U+1FFFE, U+1FFFF, U+2FFFE, U+2FFFF, ... U+10FFFE, U+10FFFF

Private Use characters in Planes 15 and 16 are limited to all the codepoints **except** the last two of each plane, which are *noncharacters*. (U+F0000–U+FFFFD, U+100000–U+10FFFD)

More here: https://en.wikipedia.org/wiki/Private_Use_Areas

**Comment by Boldewyn** [comment]
Agreed, thanks for the correction! I'll update that part.
