### ISSUE TITLE
U+FBF9 has the longest name

### ISSUE THREAD

**Issue by kenlunde** [Codepoints/awesome-codepoints#8]
Per my [tweet](https://twitter.com/ken_lunde/status/959994932478881792), U+FBF9 ﯹ ARABIC LIGATURE UIGHUR KIRGHIZ YEH WITH HAMZA ABOVE WITH ALEF MAKSURA ISOLATED FORM has the longest name of any Unicode character with 83 characters, not U+FBFB ﯻ ARABIC LIGATURE UIGHUR KIRGHIZ YEH WITH HAMZA ABOVE WITH ALEF MAKSURA INITIAL FORM with only 82.

**Comment by Boldewyn** [comment]
Well spotted! Thank you!

**Comment by kenlunde** [comment]
s/82/83/ 😉
